# Generated by Django 4.2.4 on 2023-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_province',
            field=models.CharField(choices=[('Pradesh 1', 'Pradesh 1'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudur Paschim', 'Sudur Paschim')], default='Bagmati', max_length=20),
        ),
    ]
