# Generated by Django 4.2.4 on 2023-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar', '0002_employer_employer_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_posting_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_file_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
