# Generated by Django 4.2.4 on 2023-08-30 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar', '0004_alter_jobposting_users_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
